name: Build Gateway

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

defaults:
 run:
  working-directory: ./gateway

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
